### ISSUE TITLE
TypeError: Cannot read property 'namespace' of undefined

### ISSUE THREAD

**Issue by PeteLawler** [sourcey/moxygen#11]
$sudo npm install moxygen -g
/usr/local/bin/moxygen -> /usr/local/lib/node_modules/moxygen/bin/moxygen.js
moxygen@0.6.3 /usr/local/lib/node_modules/moxygen
├── object-assign@4.1.1
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── winston@2.3.1 (cycle@1.0.3, stack-trace@0.0.9, eyes@0.1.8, isstream@0.1.2, async@1.0.0, colors@1.0.3)
├── xml2js@0.4.17 (sax@1.2.2, xmlbuilder@4.2.1)
└── handlebars@4.0.6 (async@1.5.2, source-map@0.4.4, optimist@0.6.1, uglify-js@2.8.12)

$moxygen -a -g -o api-%s.md  xml
.............
verbose: Processing compound std
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'namespace' of undefined
    at Object.module.exports.assignToNamespace (/usr/local/lib/node_modules/moxygen/src/parser.js:219:31)
    at Object.<anonymous> (/usr/local/lib/node_modules/moxygen/src/parser.js:324:22)
    at Array.forEach (native)
    at Object.module.exports.parseCompound (/usr/local/lib/node_modules/moxygen/src/parser.js:321:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/moxygen/src/parser.js:366:16)
    at Parser.<anonymous> (/usr/local/lib/node_modules/moxygen/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Object.onclosetag (/usr/local/lib/node_modules/moxygen/node_modules/xml2js/lib/xml2js.js:447:26)
    at emit (/usr/local/lib/node_modules/moxygen/node_modules/xml2js/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/usr/local/lib/node_modules/moxygen/node_modules/xml2js/node_modules/sax/lib/sax.js:645:5)

---
Not quite sure what to do at this point

**Comment by auscaster** [comment]
Can you please zip up your XML output and post it here so I can take a look :)

**Comment by auscaster** [comment]
Closing due to no response
