### ISSUE TITLE
TypeError: Cannot read property 'compound' of undefined

### ISSUE THREAD

**Issue by sailfish009** [sourcey/moxygen#13]
Hi, moxygen give me an error:

except that doxygen/doxypress, every other alternative complex and didn't worked.
sphinx+breathe+doxygen is too difficult to understand.

verbose: Parsing xml\index.xml
events.js:163
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'compound' of undefined
    at Object.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\moxygen\src\parser.js:379:50)
    at Parser.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\moxygen\node_modules\xml2js\lib\xml2js.js:489:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:191:7)
    at SAXParser.onclosetag (C:\Users\xxx\AppData\Roaming\npm\node_modules\moxygen\node_modules\xml2js\lib\xml2js.js:447:26)
    at emit (C:\Users\xxx\AppData\Roaming\npm\node_modules\moxygen\node_modules\sax\lib\sax.js:640:35)
    at emitNode (C:\Users\xxx\AppData\Roaming\npm\node_modules\moxygen\node_modules\sax\lib\sax.js:645:5)
    at closeTag (C:\Users\xxx\AppData\Roaming\npm\node_modules\moxygen\node_modules\sax\lib\sax.js:905:7)
    at SAXParser.write (C:\Users\xxx\AppData\Roaming\npm\node_modules\moxygen\node_modules\sax\lib\sax.js:1452:13)
    at Parser.exports.Parser.Parser.parseString (C:\Users\xxx\AppData\Roaming\npm\node_modules\moxygen\node_modules\xml2js\lib\xml2js.js:508:31)

**Comment by sailfish009** [comment]
never mind, created one html documentation successfully using sphinx and google template.
https://github.com/ceres-solver/ceres-solver
