### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by MichaelSteffens** [sourcey/moxygen#19]
Running moxygen on a Doxygen generated xml directory I'm running into:

```
verbose: Parsing xml/index.xml
events.js:141
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'forEach' of undefined
    at Object.module.exports.parseIndex (/usr/local/lib/node_modules/moxygen/src/parser.js:416:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/moxygen/src/parser.js:455:14)
    at Parser.<anonymous> (/usr/local/lib/node_modules/moxygen/node_modules/xml2js/lib/parser.js:303:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Object.onclosetag (/usr/local/lib/node_modules/moxygen/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/usr/local/lib/node_modules/moxygen/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/local/lib/node_modules/moxygen/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/usr/local/lib/node_modules/moxygen/node_modules/sax/lib/sax.js:889:7)
    at Object.write (/usr/local/lib/node_modules/moxygen/node_modules/sax/lib/sax.js:1436:13)
```

That reminds a lot of https://github.com/sourcey/moxygen/issues/3, so I have manually merged https://github.com/sourcey/moxygen/commit/2c067f59d8a956f488b828982c055a499ff6ebf9 into my installation. This issue seems to be at a different place (line 416), though.:

```
    412     return;
    413   },
    414 
    415   parseIndex: function (root, index, options) {
    416     index.forEach(function (element) {
    417       var doxygen, compound = root.find(element.name[0], true);
    418       var xmlParser = new xml2js.Parser({
    419         explicitChildren: true,
    420         preserveChildrenOrder: true,
    421         charsAsChildren: true
    422       });
```

**Comment by HiceS** [comment]
`TypeError: Cannot read property 'forEach' of undefined
    at Object.parseIndex (/usr/local/lib/node_modules/moxygen/src/parser.js:427:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/moxygen/src/parser.js:466:14)
    at Parser.<anonymous> (/usr/local/lib/node_modules/moxygen/node_modules/xml2js/lib/parser.js:303:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onclosetag (/usr/local/lib/node_modules/moxygen/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/usr/local/lib/node_modules/moxygen/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/local/lib/node_modules/moxygen/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/usr/local/lib/node_modules/moxygen/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/usr/local/lib/node_modules/moxygen/node_modules/sax/lib/sax.js:1436:13)`

Problem exists on macOS 10.13.5 :x:

**Comment by Dids** [comment]
Same issue, although for me it worked fine before, and I believe it was caused by an update to doxygen and how it generates the XML files?

**Comment by JoshMarler** [comment]
Just trying out moxygen so I can generate some markdown for a Docsify site. Hitting this same error. Any known fix?

**Comment by BelovitskiyDA** [comment]
I fix it by turn on `RECURSIVE` in doxygen configure
![изображение](https://github.com/sourcey/moxygen/assets/89989289/00c0dd79-04cb-4c13-8eb1-297cf7717012)

**Comment by HiceS** [comment]
We can probably close this old issue if recursive fixes this.

**Comment by auscaster** [comment]
Closing as stale. Resolved or superseded in the latest version (the parser was rewritten in TypeScript, the test suite was rebuilt, and dependencies were modernized). Please open a fresh issue with a repro against the current release if this is still applicable. Thanks!
