### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by tap** [sourcey/moxygen#3]
Output where Moxygen crashes:

```
verbose: Processing compound c74::min::attribute
verbose: Processing member m_value
verbose: Processing member m_range_args
verbose: Processing member m_range
verbose: Processing member m_enum_map
verbose: Processing member m_helper
verbose: Processing member assign_from_argument
verbose: Processing member assign_from_argument
verbose: Processing member assign_from_argument
verbose: Processing member assign_from_argument
verbose: Processing member assign_from_argument
verbose: Processing member assign_from_argument
verbose: Processing member assign_from_argument
verbose: Processing member assign_from_argument
verbose: Processing member assign_from_argument
verbose: Processing member assign_from_argument
verbose: Processing member handle_arguments
verbose: Processing member handle_arguments
verbose: Processing member copy_range
verbose: Processing member copy_range
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'forEach' of undefined
    at Object.parseMember (/usr/local/lib/node_modules/moxygen/src/parser.js:176:47)
    at Object.<anonymous> (/usr/local/lib/node_modules/moxygen/src/parser.js:293:22)
    at Array.forEach (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/moxygen/src/parser.js:288:33)
    at Array.forEach (native)
    at Object.parseCompound (/usr/local/lib/node_modules/moxygen/src/parser.js:278:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/moxygen/src/parser.js:368:16)
    at Parser.<anonymous> (/usr/local/lib/node_modules/moxygen/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
```

Presumably this is the source code on which it is choking. There are only two implementations of the `copy_range()` method:

```
	template<class T, threadsafe threadsafety>
	void attribute<T,threadsafety>::copy_range() {
		range_copy_helper<T,threadsafety>(this);
	};
		
	template<>
	void attribute<std::vector<double>>::copy_range() {
		if (!m_range.empty()) {
			// the range for this type is a low-bound and high-bound applied to all elements in the vector
			assert( m_range_args.size() == 2);
			
			m_range.resize(2);
			m_range[0][0] = m_range_args[0];
			m_range[1][0] = m_range_args[1];
		}
	};
```

**Comment by dhanjit** [comment]
Facing this same issue. Any idea how this can be resolved?

**Comment by iondune** [comment]
I have the same issue, suspect code below. Seems to have something to do with templates or overloads.

```
		class IIndexBuffer
		{

		public:

			virtual ~IIndexBuffer()
			{}

			template <typename T>
			void UploadData(vector<T> const & Data);

			virtual void UploadData(void const * Data, size_t const Elements, EValueType const ValueType) = 0;

		};
```

**Comment by iondune** [comment]
I believe [this is the problem line](https://github.com/sourcey/moxygen/blob/4404171f82fa583524e7bb01a76c7c1e26e74669/src/parser.js#L191), where `memberdef.templateparamlist[0].param` is undefined.

Just an educated guess, though.

**Comment by BotellaA** [comment]
I have the same issue... Any news about this?

**Comment by Feaisil** [comment]
It seems to be template specialization :
```
struct Class{
template<typename Type> void member(const Type& input);
};
template <typename Type> void Class::member(const Type& input){}
template <> void Class::member(const std::string& input){}
```
doxygen generates the following xml for the specialization:
```
 <memberdef kind="function" id="classClass[...]" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <templateparamlist>
        </templateparamlist>
        <type>void</type>
[...]
```
As a workaround I transformed [this](https://github.com/sourcey/moxygen/blob/4404171f82fa583524e7bb01a76c7c1e26e74669/src/parser.js#L191-L195) into:
```
          if (memberdef.templateparamlist.length > 0 && memberdef.templateparamlist.param) {
              memberdef.templateparamlist[0].param.forEach(function (param, argn) {
                m = m.concat(argn == 0 ? [] : ',');
                m = m.concat([toMarkdown(param.type)]);
                m = m.concat(param.declname ? [' ', toMarkdown(param.declname)] : []);
              });
          }
```
