### ISSUE TITLE
Moxygen Error - "TypeError: Cannot read property 'match' of undefined"

### ISSUE THREAD

**Issue by alexander-edward-ptr** [sourcey/moxygen#36]
Hey guys, am I doing something wrong?

Moxygen works fine with my ObjectiveC codebase's doxygen output, but not for my Android (Java)

I can remove some of the files and change the error, but I have too many files - it would be better just to be told the error so that I can fix it.
 
Any help would be super  👍

last verbose statement: (pretty standard output up until here)
```
verbose: Processing member function [static initializer]
```

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'match' of undefined
    at Object.parseMember (/usr/local/lib/node_modules/moxygen/src/parser.js:230:48)
    at Object.<anonymous> (/usr/local/lib/node_modules/moxygen/src/parser.js:358:22)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/usr/local/lib/node_modules/moxygen/src/parser.js:347:33)
    at Array.forEach (<anonymous>)
    at Object.parseCompound (/usr/local/lib/node_modules/moxygen/src/parser.js:335:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/moxygen/src/parser.js:445:18)
    at Parser.<anonymous> (/usr/local/lib/node_modules/moxygen/node_modules/xml2js/lib/parser.js:303:18)
    at Parser.emit (events.js:182:13)
    at SAXParser.onclosetag (/usr/local/lib/node_modules/moxygen/node_modules/xml2js/lib/parser.js:261:26)
Emitted 'error' event at:
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/moxygen/node_modules/xml2js/lib/parser.js:326:16)
    at Parser.parseString (/usr/local/lib/node_modules/moxygen/node_modules/xml2js/lib/parser.js:5:59)
    at Object.<anonymous> (/usr/local/lib/node_modules/moxygen/src/parser.js:460:17)
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

**Comment by auscaster** [comment]
Closing as stale. Resolved or superseded in the latest version (the parser was rewritten in TypeScript, the test suite was rebuilt, and dependencies were modernized). Please open a fresh issue with a repro against the current release if this is still applicable. Thanks!
