### ISSUE TITLE
AssertionError [ERR_ASSERTION]: false == true

### ISSUE THREAD

**Issue by nephatrine** [sourcey/moxygen#42]
Using Moxygen 0.8 I get a bunch of winston errors about having no transports and a `false == true` exception. **If I roll back to 0.7.12 then everything works without error** using same test project and same commandline.

```
[2/5] [MOXYGEN] Generating Documentation
FAILED: markdown/api.md 
cd /home/nephatrine/Code/kakihara/build-vscode/markdown && /usr/local/bin/moxygen --anchors --output api.md /home/nephatrine/Code/kakihara/build-vscode/xml
[winston] Attempt to write logs with no transports {"message":"Parsing /home/nephatrine/Code/kakihara/build-vscode/xml/index.xml","level":"verbose"}
[winston] Attempt to write logs with no transports {"message":"Parsing /home/nephatrine/Code/kakihara/build-vscode/xml/namespacekakihara.xml","level":"verbose"}
[winston] Attempt to write logs with no transports {"message":"Preprocessing compound kakihara","level":"verbose"}
[winston] Attempt to write logs with no transports {"message":"Parsing /home/nephatrine/Code/kakihara/build-vscode/xml/namespacekakihara_1_1math.xml","level":"verbose"}
[winston] Attempt to write logs with no transports {"message":"Preprocessing compound kakihara::math","level":"verbose"}
[winston] Attempt to write logs with no transports {"message":"Parsing /home/nephatrine/Code/kakihara/build-vscode/xml/md__l_i_c_e_n_s_e.xml","level":"verbose"}
[winston] Attempt to write logs with no transports {"message":"Preprocessing compound md_LICENSE","level":"verbose"}
[winston] Attempt to write logs with no transports {"message":"Parsing /home/nephatrine/Code/kakihara/build-vscode/xml/dir_d44c64559bbebec7f509842c48db8b23.xml","level":"verbose"}
[winston] Attempt to write logs with no transports {"message":"Preprocessing compound include","level":"verbose"}
[winston] Attempt to write logs with no transports {"message":"Parsing /home/nephatrine/Code/kakihara/build-vscode/xml/dir_ceefa81d554df2b91789412b9c8c4539.xml","level":"verbose"}
[winston] Attempt to write logs with no transports {"message":"Preprocessing compound include/kakihara","level":"verbose"}
[winston] Attempt to write logs with no transports {"message":"Parsing /home/nephatrine/Code/kakihara/build-vscode/xml/dir_b19efdc78bc6575bc11ffa57743acbba.xml","level":"verbose"}
[winston] Attempt to write logs with no transports {"message":"Preprocessing compound include/kakihara/math","level":"verbose"}
[winston] Attempt to write logs with no transports {"message":"Parsing /home/nephatrine/Code/kakihara/build-vscode/xml/indexpage.xml","level":"verbose"}
[winston] Attempt to write logs with no transports {"message":"Preprocessing compound index","level":"verbose"}
[winston] Attempt to write logs with no transports {"message":"Processing compound kakihara","level":"verbose"}
events.js:183
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: false == true
    at Console.assert (console.js:194:23)
    at toMarkdown (/usr/local/lib/node_modules/moxygen/src/parser.js:135:15)
    at copy (/usr/local/lib/node_modules/moxygen/src/parser.js:146:25)
    at Object.parseCompound (/usr/local/lib/node_modules/moxygen/src/parser.js:323:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/moxygen/src/parser.js:445:16)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/usr/local/lib/node_modules/moxygen/src/parser.js:443:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/moxygen/src/parser.js:474:9)
    at Parser.<anonymous> (/usr/local/lib/node_modules/moxygen/node_modules/xml2js/lib/parser.js:303:18)
    at emitOne (events.js:116:13)
ninja: build stopped: subcommand failed.
```

Running on Ubuntu 18.10, Doxygen 1.8.13, and NPM 5.8.0. NPM package versions installed:

```
/usr/local/lib
├─┬ moxygen@0.8.0
│ ├── commander@2.19.0
│ ├─┬ handlebars@4.1.0
│ │ ├─┬ async@2.6.2
│ │ │ └── lodash@4.17.11
│ │ ├─┬ optimist@0.6.1
│ │ │ ├── minimist@0.0.10
│ │ │ └── wordwrap@0.0.3
│ │ ├── source-map@0.6.1
│ │ └─┬ uglify-js@3.4.9
│ │   ├── commander@2.17.1
│ │   └── source-map@0.6.1 deduped
│ ├── object-assign@4.1.1
│ ├─┬ winston@3.2.1
│ │ ├── async@2.6.2 deduped
│ │ ├─┬ diagnostics@1.1.1
│ │ │ ├─┬ colorspace@1.1.1
│ │ │ │ ├─┬ color@3.0.0
│ │ │ │ │ ├─┬ color-convert@1.9.3
│ │ │ │ │ │ └── color-name@1.1.3
│ │ │ │ │ └─┬ color-string@1.5.3
│ │ │ │ │   ├── color-name@1.1.3 deduped
│ │ │ │ │   └─┬ simple-swizzle@0.2.2
│ │ │ │ │     └── is-arrayish@0.3.2
│ │ │ │ └── text-hex@1.0.0
│ │ │ ├─┬ enabled@1.0.2
│ │ │ │ └── env-variable@0.0.5
│ │ │ └─┬ kuler@1.0.1
│ │ │   └── colornames@1.1.1
│ │ ├── is-stream@1.1.0
│ │ ├─┬ logform@2.1.2
│ │ │ ├── colors@1.3.3
│ │ │ ├── fast-safe-stringify@2.0.6
│ │ │ ├── fecha@2.3.3
│ │ │ ├── ms@2.1.1
│ │ │ └── triple-beam@1.3.0 deduped
│ │ ├── one-time@0.0.4
│ │ ├─┬ readable-stream@3.1.1
│ │ │ ├── inherits@2.0.3
│ │ │ ├─┬ string_decoder@1.2.0
│ │ │ │ └── safe-buffer@5.1.2
│ │ │ └── util-deprecate@1.0.2
│ │ ├── stack-trace@0.0.10
│ │ ├── triple-beam@1.3.0
│ │ └─┬ winston-transport@4.3.0
│ │   ├─┬ readable-stream@2.3.6
│ │   │ ├── core-util-is@1.0.2
│ │   │ ├── inherits@2.0.3 deduped
│ │   │ ├── isarray@1.0.0
│ │   │ ├── process-nextick-args@2.0.0
│ │   │ ├── safe-buffer@5.1.2 deduped
│ │   │ ├─┬ string_decoder@1.1.1
│ │   │ │ └── safe-buffer@5.1.2 deduped
│ │   │ └── util-deprecate@1.0.2 deduped
│ │   └── triple-beam@1.3.0 deduped
│ └─┬ xml2js@0.4.19
│   ├── sax@1.2.4
│   └── xmlbuilder@9.0.7
```

Let me know what other information might be helpful.

**Comment by auscaster** [comment]
Closing as stale. Resolved or superseded in the latest version (the parser was rewritten in TypeScript, the test suite was rebuilt, and dependencies were modernized). Please open a fresh issue with a repro against the current release if this is still applicable. Thanks!
