### ISSUE TITLE
Winston: Unexpected Token - dependency update?

### ISSUE THREAD

**Issue by juliangaal** [sourcey/moxygen#49]
Hi,
I'm getting this error from winston, which should have been [fixed](https://github.com/winstonjs/winston-redis/issues/32#issue-380505644) in winston at least.
```
/usr/local/lib/node_modules/moxygen/node_modules/winston/lib/winston.js:11
const { warn } = require('./winston/common');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/moxygen/bin/moxygen.js:4:11)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

Are you using an older version of winston? Or can this issue be my side? 
Thanks for your help

**Comment by adamconkey** [comment]
I also have this issue.

**Comment by auscaster** [comment]
Closing as stale. Resolved or superseded in the latest version (the parser was rewritten in TypeScript, the test suite was rebuilt, and dependencies were modernized). Please open a fresh issue with a repro against the current release if this is still applicable. Thanks!
