### ISSUE TITLE
Crash with: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by loopsmark** [sourcey/moxygen#6]
This is the ouput:

Running with : moxygen --anchors --groups --output api-%s.md xml

This is the ouput it generates:

```
verbose: Parsing xml/dir_f2541a3b18981391fa76fac5599e978a.xml
verbose: Processing compound Modules
verbose: Parsing xml/dir_767e358558999a3484dff556e4638747.xml
verbose: Processing compound Modules/Bowl/src
events.js:141
      throw er; // Unhandled 'error' event
      ^

RangeError: Maximum call stack size exceeded
    at Object.<anonymous> (/usr/local/lib/node_modules/moxygen/src/compound.js:34:51)
    at Array.map (native)
    at Object.Compound.toArray (/usr/local/lib/node_modules/moxygen/src/compound.js:34:39)
    at Object.<anonymous> (/usr/local/lib/node_modules/moxygen/src/compound.js:43:37)
    at Array.forEach (native)
    at Object.Compound.toArray (/usr/local/lib/node_modules/moxygen/src/compound.js:40:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/moxygen/src/compound.js:43:37)
    at Array.forEach (native)
    at Object.Compound.toArray (/usr/local/lib/node_modules/moxygen/src/compound.js:40:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/moxygen/src/compound.js:43:37)

```

**Comment by pengi** [comment]
It seems to be that `assignClassToGroup` is called with the same compound as child.  It seems to happend if a struct in the group has the same name as the group itself:

```
/**
 * \addtogroup something
 * @{
 */

struct something {
    uint8_t placeholder;
};

/**
 * @}
 */
```

Can't really tell if there are other configurations at stake here. If there are any questions about the setup, like configuration parameters, just ask.

**Comment by auscaster** [comment]
Closing as stale. Resolved or superseded in the latest version (the parser was rewritten in TypeScript, the test suite was rebuilt, and dependencies were modernized). Please open a fresh issue with a repro against the current release if this is still applicable. Thanks!
